# Generated by Django 6.0.5 on 2026-05-26 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='identity.clan')),
                ('founding_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_families', to='identity.person')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('clan', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PersonFamilyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_family', models.CharField(choices=[('founder', 'Founder'), ('elder', 'Elder'), ('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('member', 'Member'), ('other', 'Other')], default='member', max_length=20)),
                ('joined_family_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='genealogy.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_memberships', to='identity.person')),
            ],
            options={
                'unique_together': {('person', 'family')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('parent', 'Parent'), ('father', 'Father'), ('mother', 'Mother'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt_uncle', 'Aunt/Uncle'), ('nephew_niece', 'Nephew/Niece'), ('cousin', 'Cousin'), ('in_law', 'In-Law')], max_length=20)),
                ('is_biological', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_from', to='identity.person')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_relationships', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_to', to='identity.person')),
            ],
            options={
                'ordering': ['relation_type'],
                'unique_together': {('from_person', 'to_person', 'relation_type')},
            },
        ),
    ]
